env: Development # | Production | Development
port: 8090
maxFailure: 3

# AUTH
auth:
  expireAccessToken: 3d
  expireRefreshToken: 6d
  secret: vzThJNyvMp2kV3H5
  secretClaim: vzThJNyvMp2kV3H5

# POSTGRES
postgres: # LOCAL
  username: mac
  password: yourpassword
  sslMode: disable
  host: localhost
  port: 5432
  dbName: tiketfest

# REDIS
redis:
  host: 127.0.0.1
  port: 6379
  Password: ""
  defaultDb: 0