package utilities

const (
	Success              = "success"
	Authorization        = "authorization not valid"
	InternalServiceError = "internal service error"
	EmptyValue           = "%v can not be empty"
	ValueAreadyExist     = "%v has taken"
	BadRequest           = "bad request"
	ValueNotValid        = "format %v not valid"
	Forbidden            = "access forbidden"
	MinValueMust         = "%v must be minimal %v"
	MaxValueMust         = "%v must be maximal %v"
	DataNotFound         = "%v not found"
	NumberNotValid       = "format harus berupa angka"
	ToManyRequest        = "to many request"
	InvalidAccessLogin   = "incorrect email or password"
	//PasswordIncorret     = "kata sandi salah"
	//MaxValue           = "%v tidak boleh lebih %v"
	//ShouldValue        = "%v tidak benar, nilai yang diperbolehkan: %v"
	//MinValueMust       = "%v must be minimal %v"
	//MaxValueMust       = "%v harus maksimal %v"
	//DateTimeNotValid   = "format tanggal dan waktu %v tidak benar"
	//TimeNotValid       = "format waktu %v tidak benar"
	//NumberNotValid     = "format harus berupa angka"
	//MaxPageRequest     = "tidak ada data ditemukan, gunakan filter untuk menampilkan data lainnya"
	//CantDeleteData     = "data tidak dapat dihapus"
	//CantUpdateData     = "data tidak dapat diubah"
	//AlreadyOTP         = "kode otp sebelumnya masih berlaku"
	//MaxFilterDateRange = "maksimal jarak filter kurung waktu 3 bulan"
	//MaxFailure         = "total kesalahan sebanyak 3x silahkan coba kembali %s"
)
